# Generated by Django 4.2.3 on 2023-07-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='tittle',
            new_name='title',
        ),
    ]
