# Generated by Django 4.2.3 on 2023-08-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_tittle_articlepost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='total_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
